export const ACTION_UI_SHOW_TOAST: string = 'ui.showToast';
export const ACTION_SYSTEM_CLIPBOARD_WRITE_TEXT: string = 'system.clipboard.writeText';
export const ACTION_SYSTEM_CLIPBOARD_READ_TEXT: string = 'system.clipboard.readText';
export const ACTION_SYSTEM_STORAGE_SET_ITEM: string = 'system.storage.setItem';
export const ACTION_SYSTEM_STORAGE_GET_ITEM: string = 'system.storage.getItem';
export const ACTION_SYSTEM_STORAGE_REMOVE_ITEM: string = 'system.storage.removeItem';
export const ACTION_SYSTEM_STORAGE_CLEAR: string = 'system.storage.clear';
