param([string]$HvigorPath = '')

$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$moduleRoot = Join-Path $repoRoot 'myascf_runtime'
$generatedProfile = Join-Path $moduleRoot 'BuildProfile.ets'
$generatedProfileBytes = if (Test-Path -LiteralPath $generatedProfile -PathType Leaf) {
  [IO.File]::ReadAllBytes($generatedProfile)
} else {
  $null
}

function Resolve-HvigorWrapper {
  param([string]$RequestedPath)
  $candidates = @()
  if ($RequestedPath) { $candidates += $RequestedPath }
  if ($env:HVIGORW) { $candidates += $env:HVIGORW }
  $command = Get-Command 'hvigorw.bat' -ErrorAction SilentlyContinue
  if ($command) { $candidates += $command.Source }
  if ($env:ProgramFiles) {
    $candidates += Join-Path $env:ProgramFiles 'Huawei\DevEco Studio\tools\hvigor\bin\hvigorw.bat'
  }
  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
      return (Resolve-Path -LiteralPath $candidate).Path
    }
  }
  throw 'Hvigor wrapper not found. Pass -HvigorPath or set HVIGORW.'
}

if (-not (Test-Path -LiteralPath $moduleRoot -PathType Container)) {
  throw "Runtime module not found: $moduleRoot"
}
$hvigor = Resolve-HvigorWrapper -RequestedPath $HvigorPath
$devEcoRoot = if ($env:ProgramFiles) { Join-Path $env:ProgramFiles 'Huawei\DevEco Studio' } else { '' }
if (-not $env:DEVECO_SDK_HOME -and $devEcoRoot) {
  $sdkPath = Join-Path $devEcoRoot 'sdk'
  if (Test-Path -LiteralPath $sdkPath -PathType Container) { $env:DEVECO_SDK_HOME = $sdkPath }
}
if (-not $env:JAVA_HOME -and $devEcoRoot) {
  $jbrPath = Join-Path $devEcoRoot 'jbr'
  if (Test-Path -LiteralPath $jbrPath -PathType Container) {
    $env:JAVA_HOME = $jbrPath
    $env:Path = "$jbrPath\bin;$env:Path"
  }
}

Push-Location $repoRoot
$buildStartedAt = Get-Date
try {
  & $hvigor --mode module -p product=default -p module=myascf_runtime@default -p buildMode=release assembleHar --no-daemon
  if ($LASTEXITCODE -ne 0) { throw "HAR build failed with exit code $LASTEXITCODE" }
} finally {
  Pop-Location
  if ($null -ne $generatedProfileBytes) {
    [IO.File]::WriteAllBytes($generatedProfile, $generatedProfileBytes)
  }
}

$har = Get-ChildItem -LiteralPath (Join-Path $moduleRoot 'build') -Recurse -Filter '*.har' -File |
  Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $har) { throw 'Hvigor completed but no HAR artifact was found under myascf_runtime/build.' }
$artifactState = if ($har.LastWriteTime -ge $buildStartedAt.AddSeconds(-2)) { 'generated by this build' } else { 'reused by Hvigor as up-to-date' }
Write-Output '[HAR] build successful'
Write-Output "[HAR] path: $($har.FullName)"
Write-Output "[HAR] size: $($har.Length) bytes"
Write-Output "[HAR] modified: $($har.LastWriteTime.ToString('s'))"
Write-Output "[HAR] state: $artifactState"
& node (Join-Path $repoRoot 'scripts\check-har-release.mjs') --har $har.FullName
if ($LASTEXITCODE -ne 0) { throw "HAR release check failed with exit code $LASTEXITCODE" }
